using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace dragon
{
    /// <summary>
    /// Interaction logic for history_tab.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class history_tab : ContentPage
    {
        public history_tab()
        {
            InitializeComponent();
        }
    }
}
	