using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace dragon
{
    /// <summary>
    /// Interaction logic for panda.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class panda : ContentPage
    {
        public panda()
        {
            InitializeComponent();
        }
    }
}
	