using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace dragon
{
    /// <summary>
    /// Interaction logic for theme_menu.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class theme_menu : ContentPage
    {
        public theme_menu()
        {
            InitializeComponent();
        }

        private async void DragButt_Clicked(object sender, EventArgs e)
        {

            await Navigation.PushAsync(new TheDragon());
        }

        private void DragButt_Clicked_1(object sender, EventArgs e)
        {

        }

        private void UniButt_Clicked(object sender, EventArgs e)
        {

        }

        private void calculator_Clicked(object sender, EventArgs e)
        {

        }
    }
}
	